### ISSUE TITLE
Bobby mod

### ISSUE THREAD

**Issue by MulesGaming** [Madis0/fabulously-optimized#772] opened 2023-11-27 21:02 UTC
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/bobby

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/bobby

### Source/other link

https://github.com/Johni0702/bobby

### Mod file size

 786 KB

### License

(any other license)

### What it does

Bobby mod allows for render distance's above 32 by caching visited chunks.

### Why should it be in the modpack

It allows you to increase the render distance above 32 chunks which is helpful for large servers or just seeing farther.

### Why shouldn't it be in the modpack

Useless for people who don't want to use/can't use higher render distances. Chunks need to be stored which can lead to outdated chunks in un-visited areas.

**Comment by Madis0** [comment] 2023-11-27 21:07
Duplicate of #46 and see https://github.com/Fabulously-Optimized/fabulously-optimized/issues/656 for latest stance

**Closed as not planned by Madis0** 2023-11-27 21:07 UTC
Labels: duplicate, mod
