### ISSUE TITLE
Krypton

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#74] opened 2021-06-21 06:16 UTC
**Mod name**
Krypton

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/krypton

**Modrinth link**
https://modrinth.com/mod/krypton

**Other link**
https://github.com/astei/krypton

**What it does**
Krypton is a Fabric mod that attempts to optimize the Minecraft networking stack. It derives from work done in the Velocity and Tuinity projects.

**Why should it be in the modpack**
 Reduce CPU utilization in server

**Why shouldn't it be in the modpack**
Do not provide any guarantees about Krypton's stability, compatibility with other mods, ability to be used on every server, or support for every possible setup out there.

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
Krypton will work with the Fabric API, Lithium, and Sodium and all FO mods

**Comment by Madis0** [comment] 2021-06-21 06:17
Thanks for the suggestions, but please search the issue list first. Duplicate of #9

**Closed by Madis0** 2021-06-21 06:17 UTC
Labels: mod

**Comment by Rajbir98** [comment] 2021-06-21 06:20
I searched Krypton In issues i dont found any issues related to krypton
my fault sorry

**Comment by Madis0** [comment] 2021-06-21 06:23
You probably didn't find it because the search works with open issues by default, next time look at the top tabs (Open, Closed) as well.

**Comment by Rajbir98** [comment] 2021-06-21 06:41
thanks
