### ISSUE TITLE
CIT Resewn

### ISSUE THREAD

**Issue by CodeF53** [Madis0/fabulously-optimized#136] opened 2021-09-26 00:07 UTC
### Mod name

CIT Resewn

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/cit-resewn

### Other links

https://modrinth.com/mod/cit-resewn
https://github.com/SHsuperCM/CITResewn

### What it does

Adds Optifine CIT Compatibility.

### Why should it be in the modpack

Optifine Parity.

Cleanest way to add CIT to the pack:
 - 1 mod, with definite compat instead of MCPPPP and Chime.

### Categories

New feature, Works like Optifine/Bedrock Edition/Forge/etc

**Comment by RozeFound** [comment] 2021-09-26 03:18
Duplicate of #112

**Closed** 2021-09-26 04:49 UTC
Labels: duplicate, mod
