### ISSUE TITLE
Add ResolutionControl+

### ISSUE THREAD

**Issue by Jukitsu** [Madis0/fabulously-optimized#142] opened 2021-09-30 18:14 UTC
### Mod name

ResolutionControl+

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol

### What it does

This mod allows the player to modify the rendering resolution, and can achieve a nice SuperSampling Anti aliasing effect on a Render quality x2, similar to Optifine's render quality setting in shaders

Downsides: it may be incompatible with some mods.

### Why should it be in the modpack

This mod should belong to the pretty section of the modpack, as it allows you to have some sort of antialiasing, which some people might like it.

### Why shouldn't it be in the modpack

The mod doesn't supports Fabulous Graphics and it is highly possible it is incompatible with other mods. I haven't been able to test it yet.

### Categories

Graphics optimization

**Comment by Madis0** [comment] 2021-09-30 18:20
Duplicate of #20, let's continue discussion there

**Closed by Madis0** 2021-09-30 18:20 UTC
Labels: mod
