### ISSUE TITLE
randompatches

### ISSUE THREAD

**Issue by abasgames** [Madis0/fabulously-optimized#99] opened 2021-07-23 17:37 UTC
### Mod name

randompatches-fabric

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/randompatches-fabric

### Other links

https://github.com/TheRandomLabs/RandomPatches/tree/1.16-fabric#randompatches-fabric

### What it does

it make's slow computer's able to join multiplayer server's  that's can't keepalive with 30s that introduced in Minecraft 1.13+

### Why should it be in the modpack

its absolutely important to allow player's have more time to loading and join the server's the like while having slow internet,computer

### Why shouldn't it be in the modpack

there's no Downside's

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment] 2021-07-23 17:49
Duplicate of #26

**Closed by Madis0** 2021-07-23 17:49 UTC
Labels: duplicate, mod
