### ISSUE TITLE
Entity Distance

### ISSUE THREAD

**Issue by Soham52** [Madis0/fabulously-optimized#85] opened 2021-06-29 15:47 UTC
**Describe the bug**
The Entity distance setting is not working properly.

**To Reproduce**
1. first place any mob in glass box.
2. then go away from the box, such that the mob is not rendered anymore.
3. come to such a distance that the mob will be visible if you walk only one block.
4. now turn up your entity distance setting to 500%.
5. you still wont be able to see the mob.

**Expected behavior**
the mob should have been rendered and thus, visible.

**Specifications (please complete the following information):**
 - Modpack version:1.9.1 for 1.16.5
 - Launcher: TLauncher
 - Did you upgrade or install the pack as new? If you upgraded, from what version?

**Additional context**
This does not happen with optifine

**Comment by Madis0** [comment] 2021-06-29 16:11
Hello,
I think the issue has to do with [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entityculling), so I'd suggest:
1. Disabling the mod
2. Trying if it occurs on MC 1.17 (FO 2.0.0b3)
3. If disabling helps and it still occurs on 1.17, report it to that mod with your system specs

**Comment by Soham52** [comment] 2021-06-29 16:14
> Hello,
> I think the issue has to do with [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entityculling), so I'd suggest:
> 
> 1. Disabling the mod
> 2. Trying if it occurs on MC 1.17 (FO 2.0.0b3)
> 3. If disabling helps and it still occurs on 1.17, report it to that mod with your system specs

**Comment by Soham52** [comment] 2021-06-29 16:15
> > Hello,
> > I think the issue has to do with [EntityCulling](https://www.curseforge.com/minecraft/mc-mods/entityculling), so I'd suggest:
> > 
> > 1. Disabling the mod
> > 2. Trying if it occurs on MC 1.17 (FO 2.0.0b3)
> > 3. If disabling helps and it still occurs on 1.17, report it to that mod with your system specs

I already tried this by removing EntityCulling and then trying this again , but had no success

**Comment by Madis0** [comment] 2021-06-29 16:16
Hmm. How about disabling Sodium?

**Comment by Soham52** [comment] 2021-06-29 16:23
> Hmm. How about disabling Sodium?

umm. It did fix it, but isn't Sodium the main mod which optimizes the gameplay?

**Comment by Soham52** [comment] 2021-06-29 16:24
also sodium along with lithium and phosphor did not have this problem

**Comment by Madis0** [comment] 2021-06-29 16:54
> > Hmm. How about disabling Sodium?
> 
> umm. It did fix it, but isn't Sodium the main mod which optimizes the gameplay?

Well, yes, but if you can find the mod that causes it, you can report it and get a fix. I think this is your issue: https://github.com/CaffeineMC/sodium-fabric/issues/65
Although... I'm not sure what you meant by the next message.

**Comment by Soham52** [comment] 2021-06-29 16:56
> > > Hmm. How about disabling Sodium?
> > 
> > umm. It did fix it, but isn't Sodium the main mod which optimizes the gameplay?
> 
> Well, yes, but if you can find the mod that causes it, you can report it and get a fix. I think this is your issue: https://github.com/CaffeineMC/sodium-fabric/issues/65
> Although... I'm not sure what you meant by the next message.
> 
> 

By the second message I meant that this is not an issue of sodium as it worked fine when i loaded it alone on fabric

**Comment by Madis0** [comment] 2021-06-29 17:21
Okay. Can you reproduce it in MC 1.17/FO 2.0.0b3 as well?

**Comment by Soham52** [comment] 2021-06-29 17:25
> Okay. Can you reproduce it in MC 1.17/FO 2.0.0b3 as well?

The full release for fabulously optimised mod for 1.17 is still not out, so how can I?

**Comment by Soham52** [comment] 2021-06-29 17:26
It wont be the same

**Comment by Madis0** [comment] 2021-06-29 17:30
While yes, there is no Sodium - there is Canvas instead - it could give some insight of whether it is caused by any of the mods which are there or maybe it has been fixed by vanilla 1.17 overall.

Additionally, you could try disabling those in 1.16: Hydrogen, FerriteCore, Custom Fog.

**Comment by Madis0** [comment] 2021-07-18 19:06
@Soham52 I have now included the newest stable version of Sodium in 2.1.0-beta.1. Please test if you can still reproduce it.

**Comment by Soham52** [comment] 2021-07-20 07:25
> @Soham52 I have now included the newest stable version of Sodium in 2.1.0-beta.1. Please test if you can still reproduce it.

ok i will try it

**Closed** 2021-09-05 17:29 UTC
Labels: bug
