### ISSUE TITLE
Overworld Two

### ISSUE THREAD

**Issue by Rajbir98** [Madis0/fabulously-optimized#70] opened 2021-06-21 05:42 UTC
**Mod name**
Overworld Two

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/overworld-two

**Modrinth link**
N/A

**Other link**
https://github.com/Gegy/overworld-two

**What it does**
Overworld Two is a fabric optimization mod that generates overworld and nether terrain much faster than vanilla minecraft 

**Why should it be in the modpack**
To allow more invasive optimization

**Why shouldn't it be in the modpack**
N/A

**Categories**
- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**
        N/A

**Comment by Madis0** [comment] 2021-06-21 05:44
Duplicate of #44

**Closed by Madis0** 2021-06-21 05:44 UTC
Labels: mod

**Comment by Rajbir98** [comment] 2021-06-21 05:53
Sorry
i Didnt Knowed
